#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=debugq
#SBATCH --time=1:00:00

module load jupyter
module load python/3.7

jupyter nbconvert --execute shortThickWallBubble.ipynb --ExecutePreprocessor.timeout=-1
