#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH -J cut_bubbles

module load jupyter
module load python/3.7

jupyter nbconvert --execute CutOutThickBubbles.ipynb --ExecutePreprocessor.timeout=-1

