#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=preq
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH -J av_thin_bub

module load jupyter
module load python/3.7

jupyter nbconvert --execute ThinWallBubble.ipynb --ExecutePreprocessor.timeout=-1
