#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH -J Fsurv

module load jupyter
module load python/3.7

jupyter nbconvert --execute cf_decay_rates.ipynb --ExecutePreprocessor.timeout=-1

